/**
 * This file was generated by the Jeddict
 */
package com.jpaulo.migraparanovodatabase.entidades;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * @author aluno
 */
@Entity
public class Categoria {

    @Id
    private Integer CodigoDaCategoria;

    @Basic
    private String nomeDaCategoria;

    public Integer getCodigoDaCategoria() {
        return this.CodigoDaCategoria;
    }

    public void setCodigoDaCategoria(Integer CodigoDaCategoria) {
        this.CodigoDaCategoria = CodigoDaCategoria;
    }

    public String getNomeDaCategoria() {
        return this.nomeDaCategoria;
    }

    public void setNomeDaCategoria(String nomeDaCategoria) {
        this.nomeDaCategoria = nomeDaCategoria;
    }

}
