/**
 * This file was generated by the Jeddict
 */
package com.jpaulo.migraparanovodatabase.entidades;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author aluno
 */
@Entity
public class Cliente {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer CodigoDoCliente;

    @Basic
    private String NomeDaEmpresa;

    @Basic
    private String NomeDoContato;

    @Basic
    private String CargoDoContato;

    @Basic
    private String Cidade;

    @Basic
    private String Regiao;

    @Basic
    private String Cep;

    @Basic
    private String Pais;

    @Basic
    private String Telefone;

    @Basic
    private String Fax;

    public Integer getCodigoDoCliente() {
        return this.CodigoDoCliente;
    }

    public void setCodigoDoCliente(Integer CodigoDoCliente) {
        this.CodigoDoCliente = CodigoDoCliente;
    }

    public String getNomeDaEmpresa() {
        return this.NomeDaEmpresa;
    }

    public void setNomeDaEmpresa(String NomeDaEmpresa) {
        this.NomeDaEmpresa = NomeDaEmpresa;
    }

    public String getNomeDoContato() {
        return this.NomeDoContato;
    }

    public void setNomeDoContato(String NomeDoContato) {
        this.NomeDoContato = NomeDoContato;
    }

    public String getCargoDoContato() {
        return this.CargoDoContato;
    }

    public void setCargoDoContato(String CargoDoContato) {
        this.CargoDoContato = CargoDoContato;
    }

    public String getCidade() {
        return this.Cidade;
    }

    public void setCidade(String Cidade) {
        this.Cidade = Cidade;
    }

    public String getRegiao() {
        return this.Regiao;
    }

    public void setRegiao(String Regiao) {
        this.Regiao = Regiao;
    }

    public String getCep() {
        return this.Cep;
    }

    public void setCep(String Cep) {
        this.Cep = Cep;
    }

    public String getPais() {
        return this.Pais;
    }

    public void setPais(String Pais) {
        this.Pais = Pais;
    }

    public String getTelefone() {
        return this.Telefone;
    }

    public void setTelefone(String Telefone) {
        this.Telefone = Telefone;
    }

    public String getFax() {
        return this.Fax;
    }

    public void setFax(String Fax) {
        this.Fax = Fax;
    }

}
