/**
 * This file was generated by the Jeddict
 */
package com.jpaulo.migraparanovodatabase.entidades;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author aluno
 */
@Entity
public class Pedido {

    @Id
    private Integer NumeroDoPedido;

    @Basic
    @Temporal(TemporalType.DATE)
    private Date dataDoPedido;

    @Basic
    private int via;

    @OneToOne(optional = false, targetEntity = Cliente.class)
    private Cliente CodigoDoCliente;

    public Integer getNumeroDoPedido() {
        return this.NumeroDoPedido;
    }

    public void setNumeroDoPedido(Integer NumeroDoPedido) {
        this.NumeroDoPedido = NumeroDoPedido;
    }

    public Date getDataDoPedido() {
        return this.dataDoPedido;
    }

    public void setDataDoPedido(Date dataDoPedido) {
        this.dataDoPedido = dataDoPedido;
    }

    public int getVia() {
        return this.via;
    }

    public void setVia(int via) {
        this.via = via;
    }

    public Cliente getCodigoDoCliente() {
        return this.CodigoDoCliente;
    }

    public void setCodigoDoCliente(Cliente CodigoDoCliente) {
        this.CodigoDoCliente = CodigoDoCliente;
    }

}
