/**
 * This file was generated by the Jeddict
 */
package com.jpaulo.migraparanovodatabase.entidades;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;

/**
 * @author aluno
 */
@Entity
public class Produto {

    @Id
    private Integer CodigoDoProduto;

    @Basic
    private String nomeDoProduto;

    @Basic
    private String produtosCodigoDaCategoria;

    @Basic
    private Float PrecoUnitario;

    @Basic
    private int unidadesEmEstoque;

    @Basic
    private int unidadesPedidas;

    @Basic
    private Integer nivelDeReposicao;

    @Basic
    private char descontinuado;

    @Basic
    private String quantidadePorUnidade;

    @OneToOne(targetEntity = Fornecedor.class)
    private Fornecedor CodigoDoFornecedor;

    @OneToOne(targetEntity = Categoria.class)
    private Categoria CodigoDaCategoria;

    public Integer getCodigoDoProduto() {
        return this.CodigoDoProduto;
    }

    public void setCodigoDoProduto(Integer CodigoDoProduto) {
        this.CodigoDoProduto = CodigoDoProduto;
    }

    public String getNomeDoProduto() {
        return this.nomeDoProduto;
    }

    public void setNomeDoProduto(String nomeDoProduto) {
        this.nomeDoProduto = nomeDoProduto;
    }

    public String getProdutosCodigoDaCategoria() {
        return this.produtosCodigoDaCategoria;
    }

    public void setProdutosCodigoDaCategoria(String produtosCodigoDaCategoria) {
        this.produtosCodigoDaCategoria = produtosCodigoDaCategoria;
    }

    public Float getPrecoUnitario() {
        return this.PrecoUnitario;
    }

    public void setPrecoUnitario(Float PrecoUnitario) {
        this.PrecoUnitario = PrecoUnitario;
    }

    public int getUnidadesEmEstoque() {
        return this.unidadesEmEstoque;
    }

    public void setUnidadesEmEstoque(int unidadesEmEstoque) {
        this.unidadesEmEstoque = unidadesEmEstoque;
    }

    public int getUnidadesPedidas() {
        return this.unidadesPedidas;
    }

    public void setUnidadesPedidas(int unidadesPedidas) {
        this.unidadesPedidas = unidadesPedidas;
    }

    public Integer getNivelDeReposicao() {
        return this.nivelDeReposicao;
    }

    public void setNivelDeReposicao(Integer nivelDeReposicao) {
        this.nivelDeReposicao = nivelDeReposicao;
    }

    public char getDescontinuado() {
        return this.descontinuado;
    }

    public void setDescontinuado(char descontinuado) {
        this.descontinuado = descontinuado;
    }

    public String getQuantidadePorUnidade() {
        return this.quantidadePorUnidade;
    }

    public void setQuantidadePorUnidade(String quantidadePorUnidade) {
        this.quantidadePorUnidade = quantidadePorUnidade;
    }

    public Fornecedor getCodigoDoFornecedor() {
        return this.CodigoDoFornecedor;
    }

    public void setCodigoDoFornecedor(Fornecedor CodigoDoFornecedor) {
        this.CodigoDoFornecedor = CodigoDoFornecedor;
    }

    public Categoria getCodigoDaCategoria() {
        return this.CodigoDaCategoria;
    }

    public void setCodigoDaCategoria(Categoria CodigoDaCategoria) {
        this.CodigoDaCategoria = CodigoDaCategoria;
    }

}
