package com.jpaulo.migraparanovodatabase.entidades;
// Generated 04/05/2017 14:58:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tabelao generated by hbm2java
 */
public class Tabelao  implements java.io.Serializable {


     private Integer id;
     private Integer categoriasCodigoDaCategoria;
     private String nomeDaCategoria;
     private String descricao;
     private String clientesCodigoDoCliente;
     private String clientesNomeDaEmpresa;
     private String clientesNomeDoContato;
     private String clientesCargoDoContato;
     private String clientesEndereco;
     private String clientesCidade;
     private String clientesRegiao;
     private String clientesCep;
     private String clientesPais;
     private String clientesTelefone;
     private String clientesFax;
     private Integer detalhesPedidoNumeroDoPedido;
     private Integer detalhesPedidoCodigoDoProduto;
     private Float detalhesPedidoPrecoUnitario;
     private Integer quantidade;
     private Float desconto;
     private Integer codigoDoFuncionario;
     private String sobrenome;
     private String nome;
     private String cargo;
     private String tratamento;
     private Date dataDeNascimento;
     private Date dataDeContratacao;
     private String empregadosEndereco;
     private String empregadosCidade;
     private String empregadosRegiao;
     private String empregadosCep;
     private String empregadosPais;
     private String telefoneResidencial;
     private String ramal;
     private String observacoes;
     private Integer supervisor;
     private Integer fornecedoresCodigoDoFornecedor;
     private String fornecedoresNomeDaEmpresa;
     private String fornecedoresNomeDoContato;
     private String fornecedoresCargoDoContato;
     private String fornecedoresEndereco;
     private String fornecedoresCidade;
     private String fornecedoresRegiao;
     private String fornecedoresCep;
     private String fornecedoresPais;
     private String fornecedoresTelefone;
     private String fornecedoresFax;
     private String homePage;
     private Integer pedidosNumeroDoPedido;
     private String pedidosCodigoDoCliente;
     private Integer codigoDoFuncionário;
     private Date dataDoPedido;
     private Date dataDeEntrega;
     private Date dataDeEnvio;
     private Integer via;
     private Float frete;
     private String nomeDoDestinatario;
     private String enderecoDoDestinatario;
     private String cidadeDeDestino;
     private String regiaoDeDestino;
     private String cepdeDestino;
     private String paisDeDestino;
     private Integer produtosCodigoDoProduto;
     private String nomeDoProduto;
     private Integer produtosCodigoDoFornecedor;
     private Integer produtosCodigoDaCategoria;
     private String quantidadePorUnidade;
     private Float produtosPrecoUnitario;
     private Integer unidadesEmEstoque;
     private Integer unidadesPedidas;
     private Integer nivelDeReposicao;
     private char descontinuado;
     private Integer codigoDaTransportadora;
     private String transportadorasNomeDaEmpresa;
     private String transportadorasTelefone;

    public Tabelao() {
    }

	
    public Tabelao(char descontinuado) {
        this.descontinuado = descontinuado;
    }
    public Tabelao(Integer categoriasCodigoDaCategoria, String nomeDaCategoria, String descricao, String clientesCodigoDoCliente, String clientesNomeDaEmpresa, String clientesNomeDoContato, String clientesCargoDoContato, String clientesEndereco, String clientesCidade, String clientesRegiao, String clientesCep, String clientesPais, String clientesTelefone, String clientesFax, Integer detalhesPedidoNumeroDoPedido, Integer detalhesPedidoCodigoDoProduto, Float detalhesPedidoPrecoUnitario, Integer quantidade, Float desconto, Integer codigoDoFuncionario, String sobrenome, String nome, String cargo, String tratamento, Date dataDeNascimento, Date dataDeContratacao, String empregadosEndereco, String empregadosCidade, String empregadosRegiao, String empregadosCep, String empregadosPais, String telefoneResidencial, String ramal, String observacoes, Integer supervisor, Integer fornecedoresCodigoDoFornecedor, String fornecedoresNomeDaEmpresa, String fornecedoresNomeDoContato, String fornecedoresCargoDoContato, String fornecedoresEndereco, String fornecedoresCidade, String fornecedoresRegiao, String fornecedoresCep, String fornecedoresPais, String fornecedoresTelefone, String fornecedoresFax, String homePage, Integer pedidosNumeroDoPedido, String pedidosCodigoDoCliente, Integer codigoDoFuncionário, Date dataDoPedido, Date dataDeEntrega, Date dataDeEnvio, Integer via, Float frete, String nomeDoDestinatario, String enderecoDoDestinatario, String cidadeDeDestino, String regiaoDeDestino, String cepdeDestino, String paisDeDestino, Integer produtosCodigoDoProduto, String nomeDoProduto, Integer produtosCodigoDoFornecedor, Integer produtosCodigoDaCategoria, String quantidadePorUnidade, Float produtosPrecoUnitario, Integer unidadesEmEstoque, Integer unidadesPedidas, Integer nivelDeReposicao, char descontinuado, Integer codigoDaTransportadora, String transportadorasNomeDaEmpresa, String transportadorasTelefone) {
       this.categoriasCodigoDaCategoria = categoriasCodigoDaCategoria;
       this.nomeDaCategoria = nomeDaCategoria;
       this.descricao = descricao;
       this.clientesCodigoDoCliente = clientesCodigoDoCliente;
       this.clientesNomeDaEmpresa = clientesNomeDaEmpresa;
       this.clientesNomeDoContato = clientesNomeDoContato;
       this.clientesCargoDoContato = clientesCargoDoContato;
       this.clientesEndereco = clientesEndereco;
       this.clientesCidade = clientesCidade;
       this.clientesRegiao = clientesRegiao;
       this.clientesCep = clientesCep;
       this.clientesPais = clientesPais;
       this.clientesTelefone = clientesTelefone;
       this.clientesFax = clientesFax;
       this.detalhesPedidoNumeroDoPedido = detalhesPedidoNumeroDoPedido;
       this.detalhesPedidoCodigoDoProduto = detalhesPedidoCodigoDoProduto;
       this.detalhesPedidoPrecoUnitario = detalhesPedidoPrecoUnitario;
       this.quantidade = quantidade;
       this.desconto = desconto;
       this.codigoDoFuncionario = codigoDoFuncionario;
       this.sobrenome = sobrenome;
       this.nome = nome;
       this.cargo = cargo;
       this.tratamento = tratamento;
       this.dataDeNascimento = dataDeNascimento;
       this.dataDeContratacao = dataDeContratacao;
       this.empregadosEndereco = empregadosEndereco;
       this.empregadosCidade = empregadosCidade;
       this.empregadosRegiao = empregadosRegiao;
       this.empregadosCep = empregadosCep;
       this.empregadosPais = empregadosPais;
       this.telefoneResidencial = telefoneResidencial;
       this.ramal = ramal;
       this.observacoes = observacoes;
       this.supervisor = supervisor;
       this.fornecedoresCodigoDoFornecedor = fornecedoresCodigoDoFornecedor;
       this.fornecedoresNomeDaEmpresa = fornecedoresNomeDaEmpresa;
       this.fornecedoresNomeDoContato = fornecedoresNomeDoContato;
       this.fornecedoresCargoDoContato = fornecedoresCargoDoContato;
       this.fornecedoresEndereco = fornecedoresEndereco;
       this.fornecedoresCidade = fornecedoresCidade;
       this.fornecedoresRegiao = fornecedoresRegiao;
       this.fornecedoresCep = fornecedoresCep;
       this.fornecedoresPais = fornecedoresPais;
       this.fornecedoresTelefone = fornecedoresTelefone;
       this.fornecedoresFax = fornecedoresFax;
       this.homePage = homePage;
       this.pedidosNumeroDoPedido = pedidosNumeroDoPedido;
       this.pedidosCodigoDoCliente = pedidosCodigoDoCliente;
       this.codigoDoFuncionário = codigoDoFuncionário;
       this.dataDoPedido = dataDoPedido;
       this.dataDeEntrega = dataDeEntrega;
       this.dataDeEnvio = dataDeEnvio;
       this.via = via;
       this.frete = frete;
       this.nomeDoDestinatario = nomeDoDestinatario;
       this.enderecoDoDestinatario = enderecoDoDestinatario;
       this.cidadeDeDestino = cidadeDeDestino;
       this.regiaoDeDestino = regiaoDeDestino;
       this.cepdeDestino = cepdeDestino;
       this.paisDeDestino = paisDeDestino;
       this.produtosCodigoDoProduto = produtosCodigoDoProduto;
       this.nomeDoProduto = nomeDoProduto;
       this.produtosCodigoDoFornecedor = produtosCodigoDoFornecedor;
       this.produtosCodigoDaCategoria = produtosCodigoDaCategoria;
       this.quantidadePorUnidade = quantidadePorUnidade;
       this.produtosPrecoUnitario = produtosPrecoUnitario;
       this.unidadesEmEstoque = unidadesEmEstoque;
       this.unidadesPedidas = unidadesPedidas;
       this.nivelDeReposicao = nivelDeReposicao;
       this.descontinuado = descontinuado;
       this.codigoDaTransportadora = codigoDaTransportadora;
       this.transportadorasNomeDaEmpresa = transportadorasNomeDaEmpresa;
       this.transportadorasTelefone = transportadorasTelefone;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getCategoriasCodigoDaCategoria() {
        return this.categoriasCodigoDaCategoria;
    }
    
    public void setCategoriasCodigoDaCategoria(Integer categoriasCodigoDaCategoria) {
        this.categoriasCodigoDaCategoria = categoriasCodigoDaCategoria;
    }
    public String getNomeDaCategoria() {
        return this.nomeDaCategoria;
    }
    
    public void setNomeDaCategoria(String nomeDaCategoria) {
        this.nomeDaCategoria = nomeDaCategoria;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getClientesCodigoDoCliente() {
        return this.clientesCodigoDoCliente;
    }
    
    public void setClientesCodigoDoCliente(String clientesCodigoDoCliente) {
        this.clientesCodigoDoCliente = clientesCodigoDoCliente;
    }
    public String getClientesNomeDaEmpresa() {
        return this.clientesNomeDaEmpresa;
    }
    
    public void setClientesNomeDaEmpresa(String clientesNomeDaEmpresa) {
        this.clientesNomeDaEmpresa = clientesNomeDaEmpresa;
    }
    public String getClientesNomeDoContato() {
        return this.clientesNomeDoContato;
    }
    
    public void setClientesNomeDoContato(String clientesNomeDoContato) {
        this.clientesNomeDoContato = clientesNomeDoContato;
    }
    public String getClientesCargoDoContato() {
        return this.clientesCargoDoContato;
    }
    
    public void setClientesCargoDoContato(String clientesCargoDoContato) {
        this.clientesCargoDoContato = clientesCargoDoContato;
    }
    public String getClientesEndereco() {
        return this.clientesEndereco;
    }
    
    public void setClientesEndereco(String clientesEndereco) {
        this.clientesEndereco = clientesEndereco;
    }
    public String getClientesCidade() {
        return this.clientesCidade;
    }
    
    public void setClientesCidade(String clientesCidade) {
        this.clientesCidade = clientesCidade;
    }
    public String getClientesRegiao() {
        return this.clientesRegiao;
    }
    
    public void setClientesRegiao(String clientesRegiao) {
        this.clientesRegiao = clientesRegiao;
    }
    public String getClientesCep() {
        return this.clientesCep;
    }
    
    public void setClientesCep(String clientesCep) {
        this.clientesCep = clientesCep;
    }
    public String getClientesPais() {
        return this.clientesPais;
    }
    
    public void setClientesPais(String clientesPais) {
        this.clientesPais = clientesPais;
    }
    public String getClientesTelefone() {
        return this.clientesTelefone;
    }
    
    public void setClientesTelefone(String clientesTelefone) {
        this.clientesTelefone = clientesTelefone;
    }
    public String getClientesFax() {
        return this.clientesFax;
    }
    
    public void setClientesFax(String clientesFax) {
        this.clientesFax = clientesFax;
    }
    public Integer getDetalhesPedidoNumeroDoPedido() {
        return this.detalhesPedidoNumeroDoPedido;
    }
    
    public void setDetalhesPedidoNumeroDoPedido(Integer detalhesPedidoNumeroDoPedido) {
        this.detalhesPedidoNumeroDoPedido = detalhesPedidoNumeroDoPedido;
    }
    public Integer getDetalhesPedidoCodigoDoProduto() {
        return this.detalhesPedidoCodigoDoProduto;
    }
    
    public void setDetalhesPedidoCodigoDoProduto(Integer detalhesPedidoCodigoDoProduto) {
        this.detalhesPedidoCodigoDoProduto = detalhesPedidoCodigoDoProduto;
    }
    public Float getDetalhesPedidoPrecoUnitario() {
        return this.detalhesPedidoPrecoUnitario;
    }
    
    public void setDetalhesPedidoPrecoUnitario(Float detalhesPedidoPrecoUnitario) {
        this.detalhesPedidoPrecoUnitario = detalhesPedidoPrecoUnitario;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }
    public Float getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(Float desconto) {
        this.desconto = desconto;
    }
    public Integer getCodigoDoFuncionario() {
        return this.codigoDoFuncionario;
    }
    
    public void setCodigoDoFuncionario(Integer codigoDoFuncionario) {
        this.codigoDoFuncionario = codigoDoFuncionario;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getTratamento() {
        return this.tratamento;
    }
    
    public void setTratamento(String tratamento) {
        this.tratamento = tratamento;
    }
    public Date getDataDeNascimento() {
        return this.dataDeNascimento;
    }
    
    public void setDataDeNascimento(Date dataDeNascimento) {
        this.dataDeNascimento = dataDeNascimento;
    }
    public Date getDataDeContratacao() {
        return this.dataDeContratacao;
    }
    
    public void setDataDeContratacao(Date dataDeContratacao) {
        this.dataDeContratacao = dataDeContratacao;
    }
    public String getEmpregadosEndereco() {
        return this.empregadosEndereco;
    }
    
    public void setEmpregadosEndereco(String empregadosEndereco) {
        this.empregadosEndereco = empregadosEndereco;
    }
    public String getEmpregadosCidade() {
        return this.empregadosCidade;
    }
    
    public void setEmpregadosCidade(String empregadosCidade) {
        this.empregadosCidade = empregadosCidade;
    }
    public String getEmpregadosRegiao() {
        return this.empregadosRegiao;
    }
    
    public void setEmpregadosRegiao(String empregadosRegiao) {
        this.empregadosRegiao = empregadosRegiao;
    }
    public String getEmpregadosCep() {
        return this.empregadosCep;
    }
    
    public void setEmpregadosCep(String empregadosCep) {
        this.empregadosCep = empregadosCep;
    }
    public String getEmpregadosPais() {
        return this.empregadosPais;
    }
    
    public void setEmpregadosPais(String empregadosPais) {
        this.empregadosPais = empregadosPais;
    }
    public String getTelefoneResidencial() {
        return this.telefoneResidencial;
    }
    
    public void setTelefoneResidencial(String telefoneResidencial) {
        this.telefoneResidencial = telefoneResidencial;
    }
    public String getRamal() {
        return this.ramal;
    }
    
    public void setRamal(String ramal) {
        this.ramal = ramal;
    }
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }
    public Integer getSupervisor() {
        return this.supervisor;
    }
    
    public void setSupervisor(Integer supervisor) {
        this.supervisor = supervisor;
    }
    public Integer getFornecedoresCodigoDoFornecedor() {
        return this.fornecedoresCodigoDoFornecedor;
    }
    
    public void setFornecedoresCodigoDoFornecedor(Integer fornecedoresCodigoDoFornecedor) {
        this.fornecedoresCodigoDoFornecedor = fornecedoresCodigoDoFornecedor;
    }
    public String getFornecedoresNomeDaEmpresa() {
        return this.fornecedoresNomeDaEmpresa;
    }
    
    public void setFornecedoresNomeDaEmpresa(String fornecedoresNomeDaEmpresa) {
        this.fornecedoresNomeDaEmpresa = fornecedoresNomeDaEmpresa;
    }
    public String getFornecedoresNomeDoContato() {
        return this.fornecedoresNomeDoContato;
    }
    
    public void setFornecedoresNomeDoContato(String fornecedoresNomeDoContato) {
        this.fornecedoresNomeDoContato = fornecedoresNomeDoContato;
    }
    public String getFornecedoresCargoDoContato() {
        return this.fornecedoresCargoDoContato;
    }
    
    public void setFornecedoresCargoDoContato(String fornecedoresCargoDoContato) {
        this.fornecedoresCargoDoContato = fornecedoresCargoDoContato;
    }
    public String getFornecedoresEndereco() {
        return this.fornecedoresEndereco;
    }
    
    public void setFornecedoresEndereco(String fornecedoresEndereco) {
        this.fornecedoresEndereco = fornecedoresEndereco;
    }
    public String getFornecedoresCidade() {
        return this.fornecedoresCidade;
    }
    
    public void setFornecedoresCidade(String fornecedoresCidade) {
        this.fornecedoresCidade = fornecedoresCidade;
    }
    public String getFornecedoresRegiao() {
        return this.fornecedoresRegiao;
    }
    
    public void setFornecedoresRegiao(String fornecedoresRegiao) {
        this.fornecedoresRegiao = fornecedoresRegiao;
    }
    public String getFornecedoresCep() {
        return this.fornecedoresCep;
    }
    
    public void setFornecedoresCep(String fornecedoresCep) {
        this.fornecedoresCep = fornecedoresCep;
    }
    public String getFornecedoresPais() {
        return this.fornecedoresPais;
    }
    
    public void setFornecedoresPais(String fornecedoresPais) {
        this.fornecedoresPais = fornecedoresPais;
    }
    public String getFornecedoresTelefone() {
        return this.fornecedoresTelefone;
    }
    
    public void setFornecedoresTelefone(String fornecedoresTelefone) {
        this.fornecedoresTelefone = fornecedoresTelefone;
    }
    public String getFornecedoresFax() {
        return this.fornecedoresFax;
    }
    
    public void setFornecedoresFax(String fornecedoresFax) {
        this.fornecedoresFax = fornecedoresFax;
    }
    public String getHomePage() {
        return this.homePage;
    }
    
    public void setHomePage(String homePage) {
        this.homePage = homePage;
    }
    public Integer getPedidosNumeroDoPedido() {
        return this.pedidosNumeroDoPedido;
    }
    
    public void setPedidosNumeroDoPedido(Integer pedidosNumeroDoPedido) {
        this.pedidosNumeroDoPedido = pedidosNumeroDoPedido;
    }
    public String getPedidosCodigoDoCliente() {
        return this.pedidosCodigoDoCliente;
    }
    
    public void setPedidosCodigoDoCliente(String pedidosCodigoDoCliente) {
        this.pedidosCodigoDoCliente = pedidosCodigoDoCliente;
    }
    public Integer getCodigoDoFuncionário() {
        return this.codigoDoFuncionário;
    }
    
    public void setCodigoDoFuncionário(Integer codigoDoFuncionário) {
        this.codigoDoFuncionário = codigoDoFuncionário;
    }
    public Date getDataDoPedido() {
        return this.dataDoPedido;
    }
    
    public void setDataDoPedido(Date dataDoPedido) {
        this.dataDoPedido = dataDoPedido;
    }
    public Date getDataDeEntrega() {
        return this.dataDeEntrega;
    }
    
    public void setDataDeEntrega(Date dataDeEntrega) {
        this.dataDeEntrega = dataDeEntrega;
    }
    public Date getDataDeEnvio() {
        return this.dataDeEnvio;
    }
    
    public void setDataDeEnvio(Date dataDeEnvio) {
        this.dataDeEnvio = dataDeEnvio;
    }
    public Integer getVia() {
        return this.via;
    }
    
    public void setVia(Integer via) {
        this.via = via;
    }
    public Float getFrete() {
        return this.frete;
    }
    
    public void setFrete(Float frete) {
        this.frete = frete;
    }
    public String getNomeDoDestinatario() {
        return this.nomeDoDestinatario;
    }
    
    public void setNomeDoDestinatario(String nomeDoDestinatario) {
        this.nomeDoDestinatario = nomeDoDestinatario;
    }
    public String getEnderecoDoDestinatario() {
        return this.enderecoDoDestinatario;
    }
    
    public void setEnderecoDoDestinatario(String enderecoDoDestinatario) {
        this.enderecoDoDestinatario = enderecoDoDestinatario;
    }
    public String getCidadeDeDestino() {
        return this.cidadeDeDestino;
    }
    
    public void setCidadeDeDestino(String cidadeDeDestino) {
        this.cidadeDeDestino = cidadeDeDestino;
    }
    public String getRegiaoDeDestino() {
        return this.regiaoDeDestino;
    }
    
    public void setRegiaoDeDestino(String regiaoDeDestino) {
        this.regiaoDeDestino = regiaoDeDestino;
    }
    public String getCepdeDestino() {
        return this.cepdeDestino;
    }
    
    public void setCepdeDestino(String cepdeDestino) {
        this.cepdeDestino = cepdeDestino;
    }
    public String getPaisDeDestino() {
        return this.paisDeDestino;
    }
    
    public void setPaisDeDestino(String paisDeDestino) {
        this.paisDeDestino = paisDeDestino;
    }
    public Integer getProdutosCodigoDoProduto() {
        return this.produtosCodigoDoProduto;
    }
    
    public void setProdutosCodigoDoProduto(Integer produtosCodigoDoProduto) {
        this.produtosCodigoDoProduto = produtosCodigoDoProduto;
    }
    public String getNomeDoProduto() {
        return this.nomeDoProduto;
    }
    
    public void setNomeDoProduto(String nomeDoProduto) {
        this.nomeDoProduto = nomeDoProduto;
    }
    public Integer getProdutosCodigoDoFornecedor() {
        return this.produtosCodigoDoFornecedor;
    }
    
    public void setProdutosCodigoDoFornecedor(Integer produtosCodigoDoFornecedor) {
        this.produtosCodigoDoFornecedor = produtosCodigoDoFornecedor;
    }
    public Integer getProdutosCodigoDaCategoria() {
        return this.produtosCodigoDaCategoria;
    }
    
    public void setProdutosCodigoDaCategoria(Integer produtosCodigoDaCategoria) {
        this.produtosCodigoDaCategoria = produtosCodigoDaCategoria;
    }
    public String getQuantidadePorUnidade() {
        return this.quantidadePorUnidade;
    }
    
    public void setQuantidadePorUnidade(String quantidadePorUnidade) {
        this.quantidadePorUnidade = quantidadePorUnidade;
    }
    public Float getProdutosPrecoUnitario() {
        return this.produtosPrecoUnitario;
    }
    
    public void setProdutosPrecoUnitario(Float produtosPrecoUnitario) {
        this.produtosPrecoUnitario = produtosPrecoUnitario;
    }
    public Integer getUnidadesEmEstoque() {
        return this.unidadesEmEstoque;
    }
    
    public void setUnidadesEmEstoque(Integer unidadesEmEstoque) {
        this.unidadesEmEstoque = unidadesEmEstoque;
    }
    public Integer getUnidadesPedidas() {
        return this.unidadesPedidas;
    }
    
    public void setUnidadesPedidas(Integer unidadesPedidas) {
        this.unidadesPedidas = unidadesPedidas;
    }
    public Integer getNivelDeReposicao() {
        return this.nivelDeReposicao;
    }
    
    public void setNivelDeReposicao(Integer nivelDeReposicao) {
        this.nivelDeReposicao = nivelDeReposicao;
    }
    public char getDescontinuado() {
        return this.descontinuado;
    }
    
    public void setDescontinuado(char descontinuado) {
        this.descontinuado = descontinuado;
    }
    public Integer getCodigoDaTransportadora() {
        return this.codigoDaTransportadora;
    }
    
    public void setCodigoDaTransportadora(Integer codigoDaTransportadora) {
        this.codigoDaTransportadora = codigoDaTransportadora;
    }
    public String getTransportadorasNomeDaEmpresa() {
        return this.transportadorasNomeDaEmpresa;
    }
    
    public void setTransportadorasNomeDaEmpresa(String transportadorasNomeDaEmpresa) {
        this.transportadorasNomeDaEmpresa = transportadorasNomeDaEmpresa;
    }
    public String getTransportadorasTelefone() {
        return this.transportadorasTelefone;
    }
    
    public void setTransportadorasTelefone(String transportadorasTelefone) {
        this.transportadorasTelefone = transportadorasTelefone;
    }




}


