/**
 * This file was generated by the Jeddict
 */
package com.jpaulo.migraparanovodatabase.entidades;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author aluno
 */
@Entity
public class Transportadora {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer codigoDaTransportadora;

    @Basic
    private String NomeDaEmpresa;

    @Basic
    private String Telefone;

    public Integer getCodigoDaTransportadora() {
        return this.codigoDaTransportadora;
    }

    public void setCodigoDaTransportadora(Integer codigoDaTransportadora) {
        this.codigoDaTransportadora = codigoDaTransportadora;
    }

    public String getNomeDaEmpresa() {
        return this.NomeDaEmpresa;
    }

    public void setNomeDaEmpresa(String NomeDaEmpresa) {
        this.NomeDaEmpresa = NomeDaEmpresa;
    }

    public String getTelefone() {
        return this.Telefone;
    }

    public void setTelefone(String Telefone) {
        this.Telefone = Telefone;
    }

}
